ALTER SESSION SET CURRENT_SCHEMA = DOCKERWILDFLY; 

CREATE TABLE "DOCKERWILDFLY"."EXAMPLE_TABLE"
(
   F_ID varchar(36) PRIMARY KEY NOT NULL,
   F_VALUE varchar(50) NOT NULL,
   F_CREATE_TIMESTAMP timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
   F_CHANGE_DATE timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
)
;
